(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(exec-path-from-shell-arguments (quote ("-l")))
 '(global-linum-mode t)
 '(package-selected-packages
   (quote
    (yasnippet-snippets writeroom-mode visual-fill-column treemacs-projectile treemacs-magit treemacs-evil symon symbol-overlay string-inflection spaceline-all-the-icons password-generator overseer nameless magit-svn helm-xref helm-purpose window-purpose imenu-list helm-ls-git helm-git-grep gitignore-templates flycheck-package package-lint evil-textobj-line evil-lion evil-goggles evil-cleverparens paredit editorconfig doom-modeline shrink-path all-the-icons memoize devdocs centered-cursor-mode hybrid-mode font-lock+ dotenv-mode pdf-tools tablist names chinese-word-at-point pyim pyim-basedict xr pangu-spacing find-by-pinyin-dired chinese-conv ace-pinyin pinyinlib helm-ctest cmake-mode cmake-ide levenshtein lsp-ui lsp-treemacs helm-lsp cquery company-lsp ccls lsp-mode dash-functional protobuf-mode toml-mode racer helm-rtags google-c-style godoctor go-tag go-rename go-impl go-guru go-gen-test go-fill-struct go-eldoc flycheck-ycmd flycheck-rust flycheck-rtags disaster cpp-auto-include company-ycmd ycmd request-deferred deferred company-rtags rtags company-go go-mode company-c-headers clang-format cargo rust-mode org-cliplink org-brain helm-org-rifle helm-org evil-org browse-at-remote org-category-capture alert log4e gntp fringe-helper git-gutter+ git-gutter flyspell-correct flycheck helm-gitignore helm-company helm-c-yasnippet flyspell-correct-helm helm-themes helm-swoop helm-projectile helm-mode-manager helm-flx helm-descbinds helm-ag ace-jump-helm-line helm helm-core youdao-dictionary ws-butler winum which-key wgrep volatile-highlights vi-tilde-fringe uuidgen use-package unfill toc-org spaceline smex smeargle restart-emacs request rainbow-delimiters popwin persp-mode pcre2el paradox orgit org-projectile org-present org-pomodoro org-mime org-download org-bullets open-junk-file neotree mwim move-text mmm-mode markdown-toc magit-gitflow macrostep lorem-ipsum linum-relative link-hint ivy-hydra indent-guide hungry-delete htmlize hl-todo highlight-parentheses highlight-numbers highlight-indentation helm-make google-translate golden-ratio gnuplot gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link git-gutter-fringe git-gutter-fringe+ gh-md fuzzy flyspell-correct-ivy flycheck-pos-tip flx-ido fill-column-indicator fancy-battery eyebrowse expand-region exec-path-from-shell evil-visualstar evil-visual-mark-mode evil-unimpaired evil-tutor evil-surround evil-search-highlight-persist evil-numbers evil-nerd-commenter evil-mc evil-matchit evil-magit evil-lisp-state evil-indent-plus evil-iedit-state evil-exchange evil-escape evil-ediff evil-args evil-anzu eval-sexp-fu elisp-slime-nav dumb-jump diminish diff-hl define-word counsel-projectile company-statistics column-enforce-mode clean-aindent-mode auto-yasnippet auto-highlight-symbol auto-dictionary auto-compile aggressive-indent adaptive-wrap ace-window ace-link ac-ispell)))
 '(pdf-view-incompatible-modes nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
